import "./globals.css";
import Header from "../../Layout/Header/Index";
import Footer from "../../Layout/Footer/Index";
import { Yantramanav } from 'next/font/google';


const yantramanav = Yantramanav({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  variable: '--font-yantramanav',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${yantramanav.variable}`}>
      <body className="font-sans">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
